pipeline {
    agent any

    environment {
        def sonarHome = tool 'SonarQube Scanner'
        def jdkSonar = tool 'jdk11'
    }
    tools {
        maven 'maven-latest'
        jdk 'jdk8'
    }
    stages {
        // Build Initialize
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }
        // Build
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        // SonarQube Scanner
        stage('SonarQube analysis') {
            steps {
                script {
                    withSonarQubeEnv('SonarQube') { 
                        sh """
                        export JAVA_HOME=${jdkSonar}
                        ${sonarHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=hello-world-maven \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=http://192.168.0.4:9000 \
                        -Dsonar.login=b3bd94551937c4369c3cd522cfbf7d94129b31d1 \
                        -Dsonar.java.binaries=target/classes"""
                    }
                }
            }
        }
        // Tests
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        // Delivering
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
